title: Team Project
description: "A personal Repo for Tri2"
owner_name: Zafeer Ahmed
github_username: ZafeerA123
github_repo: "Personal2"
baseurl: "/Personal2"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ZafeerA123/Personal2"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
